 # Publish all joint states
joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50

# Control all joints
arm_controller:
  type: "arm_control/JointTrajectoryController"  # arm_control is a namespace defined in the src/joint/trajectory_controller.cpp
  joints:
  - panda_arm_joint1
  - panda_arm_joint2
  - panda_arm_joint3
  - panda_arm_joint4
  - panda_arm_joint5
  - panda_arm_joint6
  - panda_arm_joint7


  gains:
   panda_arm_joint1: {p: 20,  d: 0}
   panda_arm_joint2: {p: 20,  d: 0, i: 2}
   panda_arm_joint3: {p: 10,  d: 0}
   panda_arm_joint4: {p: 20,  d: 0, i: 2}
   panda_arm_joint5: {p: 1,  d: 0}
   panda_arm_joint6: {p: 1,  d: 0}
   panda_arm_joint7: {p: 1,  d: 0}


    # panda_arm_joint1: {p: 80000,  d: 1, i: 500}  # those are with mass for hand and fingers =1 
    # panda_arm_joint2: {p: 100000,  d: 10, i: 700} 
    # panda_arm_joint3: {p: 50000,  d: 0.5, i: 50}
    # panda_arm_joint4: {p: 500000,  d: 60, i: 700}
    # panda_arm_joint5: {p: 50000,  d: 0.5, i: 5}
    # panda_arm_joint6: {p: 500000,  d: 30, i: 700}
    # panda_arm_joint7: {p: 1000,  d: 0.5, i: 10}

# hand_controller:
#     type: effort_controllers/JointTrajectoryController
#     joints:
#         - panda_arm_finger_joint1
#         - panda_arm_finger_joint2

#     gains:
#         panda_arm_finger_joint1: { p: 5, d: 3.0, i: 0, i_clamp: 1 }
#         panda_arm_finger_joint2: { p: 5, d: 1.0, i: 0, i_clamp: 1 }

#     state_publish_rate: 25


