controller_list:
  - name: arm0/arm0_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - arm0_joint1
      - arm0_joint2
      - arm0_joint3
      - arm0_joint4
      - arm0_joint5
      - arm0_joint6
      - arm0_joint7
  - name: arm0/arm0_hand_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - arm0_finger_joint1
      - arm0_finger_joint2
  - name: arm1/arm1_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - arm1_joint1
      - arm1_joint2
      - arm1_joint3
      - arm1_joint4
      - arm1_joint5
      - arm1_joint6
      - arm1_joint7
  - name: arm1/arm1_hand_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - arm1_finger_joint1
      - arm1_finger_joint2
