arm0:
  joint_state_controller:
    type: "joint_state_controller/JointStateController"
    publish_rate: 50

  arm0_controller:
    type: "effort_controllers/JointTrajectoryController"
    joints:
      - panda_arm_joint1
      - panda_arm_joint2
      - panda_arm_joint3
      - panda_arm_joint4
      - panda_arm_joint5
      - panda_arm_joint6
      - panda_arm_joint7

    gains:
      panda_arm_joint1: {p: 12000, i: 0, d: 10, i_clamp: 10}
      panda_arm_joint2: {p: 30000, i: 50, d: 10, i_clamp: 10}
      panda_arm_joint3: {p: 18000, i: 1, d: 50, i_clamp: 1}
      panda_arm_joint4: {p: 18000, i: 10, d: 70, i_clamp: 10}
      panda_arm_joint5: {p: 12000, i: 1, d: 70, i_clamp: 1}
      panda_arm_joint6: {p: 7000, i: 0.01, d: 50, i_clamp: 1}
      panda_arm_joint7: {p: 2000, i: 0, d: 20, i_clamp: 1}
  
    state_publish_rate: 25
  
    #constraints:
      #goal_time: 2.0

  arm0_hand_controller:
    type: "effort_controllers/JointTrajectoryController"
    joints:
      - gripper_finger_joint1
      - gripper_finger_joint2
    gains:
      gripper_finger_joint1: {p: 5, d: 3.0, i: 0, i_clamp: 1}
      gripper_finger_joint2: {p: 5, d: 3.0, i: 0, i_clamp: 1}
    state_publish_rate: 25

